[workspace]
members = [
    "crates/base",
    "crates/engine",
    "crates/pal",
    "crates/winit",
]
resolver = "2"

[workspace.dependencies]
anstream = "1.0.0"
ecow = "0.2.6"
expect-test = "1.5.1"
ignore = "0.4.24"
notify-debouncer-full = "0.5.0"
parking_lot = "0.12.5"
relative-path = "1.9.3"
serde = "1.0.228"
slotmap = "1.1.1"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
facet = "0.44.3"
winit = "0.30.13"
femtovg = "0.23.1"
glutin = "0.32.3"
glutin-winit = "0.5.0"
raw-window-handle = "0.6.2"
