[package]
name = "pixui-winit"
version = "0.1.0"
edition = "2024"
description = "Winit integration crate for the pixui project"
license = "MIT"
repository = "https://github.com/manuel-woelker/pixui"

[dependencies]
facet = { workspace = true }
femtovg = { workspace = true }
glutin = { workspace = true }
glutin-winit = { workspace = true }
pixui-base = { path = "../base", version = "0.1.0" }
pixui-engine = { path = "../engine", version = "0.1.0" }
pixui-pal = { path = "../pal", version = "0.1.0" }
raw-window-handle = { workspace = true }
winit = { workspace = true }
