[package]
name = "pixui-example-showcase"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
pixui-base = { path = "../../crates/base" }
pixui-reflect = { path = "../../crates/reflect" }
pixui-engine = { path = "../../crates/engine" }
pixui-gui = { path = "../../crates/gui" }
