[package]
name = "pixui-example-todo"
version.workspace = true
edition.workspace = true
publish = false
default-run = "pixui-example-todo"

[dependencies]
pixui-base = { path = "../../crates/base" }
pixui-reflect = { path = "../../crates/reflect" }
pixui-engine = { path = "../../crates/engine" }
pixui-gui = { path = "../../crates/gui" }
