[package]
name = "pixui-engine"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
crossbeam-channel = "0.5.17"
pixui-base = { path = "../base" }
pixui-reflect = { path = "../reflect" }
pixui-reflect-macros = { path = "../reflect-macros" }

[dev-dependencies]
expect-test = "1.5"
