[package]
name = "pixui-engine"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
fontdue = "=0.9.4"
etagere = "=0.2.15"
crossbeam-channel = "0.5.17"
pixui-base = { path = "../base" }
pixui-reflect = { path = "../reflect" }
pixui-reflect-macros = { path = "../reflect-macros" }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
ferrocat-po = "=0.12.0"

[dev-dependencies]
png = "0.18.1"
expect-test = "1.5"
