[package]
name = "pixui-pal"
version = "0.1.0"
edition = "2024"
description = "Platform abstraction layer for the pixui project"
license = "MIT"
repository = "https://github.com/manuel-woelker/pixui"

[dependencies]
pixui-base = { path = "../base", version = "0.1.0" }
expect-test = { workspace = true }
ignore = { workspace = true }
notify-debouncer-full = { workspace = true }
relative-path = { workspace = true }
tokio = { version = "1.44.2", features = ["io-util", "macros", "process", "rt-multi-thread", "sync"] }
